### ISSUE TITLE
make PISM compile with petsc-3.3

### ISSUE THREAD

**Issue by aaschwanden** [pism/pism#69]
Title says it all. With petsc 3.3 out of the door, we should make PISM compiling with 3.3.

Currently, compilation fails with:

[  5%] Building CXX object src/CMakeFiles/pismutil.dir/base/enthalpyConverter.cc.o
/Users/andy/pism-dev/src/base/enthalpyConverter.cc: In member function ‘virtual PetscErrorCode EnthalpyConverter::viewConstants(_p_PetscViewer_) const’:
/Users/andy/pism-dev/src/base/enthalpyConverter.cc:47: error: ‘PetscTypeCompare’ was not declared in this scope
make[2]: *_\* [src/CMakeFiles/pismutil.dir/base/enthalpyConverter.cc.o] Error 1
make[1]: **\* [src/CMakeFiles/pismutil.dir/all] Error 2
make: **\* [all] Error 2
